# Generated by Django 3.2.12 on 2024-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clip_path',
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='faces-seen/'),
        ),
    ]
