# Generated by Django 3.2.12 on 2024-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20240616_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='event-clips/'),
        ),
    ]
