# Generated by Django 3.2.12 on 2024-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_event_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='event_clips/'),
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='faces_seen/'),
        ),
    ]
