# Generated by Django 4.2 on 2024-07-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20240616_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
