# Generated by Django 4.2 on 2024-07-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_emailsettings_smtp_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
