# Generated by Django 4.2 on 2024-07-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_face_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='tagged',
        ),
    ]
