# Generated by Django 4.2 on 2024-07-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_camera_camerasystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerasystem',
            name='camera1',
        ),
        migrations.RemoveField(
            model_name='camerasystem',
            name='camera2',
        ),
        migrations.RemoveField(
            model_name='camerasystem',
            name='camera3',
        ),
        migrations.RemoveField(
            model_name='camerasystem',
            name='camera4',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='CameraSystem',
        ),
    ]
