# Generated by Django 4.2 on 2024-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_remove_face_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
