# Generated by Django 4.2 on 2024-07-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
