# Generated by Django 4.2 on 2024-07-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_camera_password_camera_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='device_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('ip', 'IP Camera'), ('usb', 'USB Camera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
