# Generated by Django 4.2 on 2024-07-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_camera_device_index_alter_camera_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
