# Generated by Django 4.2 on 2024-08-18 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_audiodevicesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodevicesetting',
            name='audio_device_name',
        ),
        migrations.AddField(
            model_name='audiodevicesetting',
            name='audio_device',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='audiodevicesetting',
            name='camera_index',
            field=models.CharField(default='default_camera', max_length=255),
        ),
        migrations.AlterField(
            model_name='audiodevicesetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
