# Generated by Django 4.2 on 2024-08-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0013_remove_audiodevicesetting_audio_device_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodevicesetting',
            name='camera_index',
        ),
        migrations.AddField(
            model_name='audiodevicesetting',
            name='device_path',
            field=models.CharField(default='/dev/unknown', max_length=255),
            preserve_default=False,
        ),
    ]
