# Generated by Django 4.2 on 2024-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_remove_audiodevicesetting_camera_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.TextField()),
            ],
        ),
    ]
