# Generated by Django 4.2 on 2024-08-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0015_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
